#ifndef IO_RESERVA_H
#define IO_RESERVA_H

#define GPIO_OVERFLOW 31
#define GPIO_OVERFLOW_BITS 1

#define GPIO_HELLO_WORLD 0
#define GPIO_HELLO_WORLD_BITS 8

#define GPIO_LATIDO 16
#define GPIO_LATIDO_BITS 8

#define GPIO_SERIE_ERROR 30
#define GPIO_SERIE_ERROR_BITS 1

#define GPIO_COMANDO_ERRONEO 29
#define GPIO_COMANDO_ERRONEO_BITS 1

#endif
